### ISSUE TITLE
Publishing Migrate files from other packages.

### ISSUE THREAD

**Issue by kirananils** [orchestral/platform#48]
In the Packages such as https://github.com/rtconner/laravel-tagging , the migration files are moved to <b>base_path/database/ </b> according to laravel 5 folder structure. Where as in Orchestra's folder structure it needed to be moved to the path <b>base_path/resources/database/ </b>
Boot for the above package.
<pre>
public function boot() {
$this->publishes([
__DIR__.'/../../../config/tagging.php' => config_path('tagging.php'),
__DIR__.'/../../../migrations/2014_01_07_073615_create_tagged_table.php' => base_path('database/migrations/2014_01_07_073615_create_tagged_table.php'),
__DIR__.'/../../../migrations/2014_01_07_073615_create_tags_table.php' => base_path('database/migrations/2014_01_07_073615_create_tags_table.php'),
]);
}
</pre>

I have to manually move the files from /database to /resources/database in order for migration to work after publishing the package. Is there any work around for this issue.

**Comment by crynobone** [comment]
> I have to manually move the files from /database to /resources/database in order for migration to work after publishing the package.

It should actually use `$this->app->databasePath()` <https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Application.php#L303>

**Comment by kirananils** [comment]
ok.

**Comment by crynobone** [comment]
I'm also sent a PR to add `database_path()` helper to laravel/framework#8190

**Comment by kirananils** [comment]
Ok... Thank You...
