### ISSUE TITLE
Welcome text missing something

### ISSUE THREAD

**Issue by khalid-hussain** [orchestral/platform#55]
Assalamuʻalaikum,

Upon installation, I'm presented with the following screen:

![screencapture-localhost-orchestra-website-public-admin-1450535331872](https://cloud.githubusercontent.com/assets/3102714/11997147/0d5cc27e-aaaf-11e5-8c04-419e1f28d485.png)

It says "...here are a few things most people do first when they set up a new Orchestra Platform site." However, I don't see anything. Is it missing something or is something wrong with my browser?

Thanks for your time.

**Comment by crynobone** [comment]
I'm planning to work on that before final 3.2.0, any ideas?

Should continue this discussion at orchestral/foundation#186
