### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by unixtime** [orchestral/platform#58]
I am sorry in advance if this is the wrong place to ask a question.
Is LDAP/AD support on the roadmap?

Thank you.

**Comment by crynobone** [comment]
Nope, but I know @stevebauman has been building some LDAP integration for Orchestra Platform https://github.com/stevebauman/maintenance

**Comment by unixtime** [comment]
Thank you, I just noticed you have replied a week ago. And thank you for developing awesome Orchestral.
