### ISSUE TITLE
Admin user creation issue on PHP 7.3.11

### ISSUE THREAD

**Issue by vbasky** [orchestral/platform#68]
When I try to create a new user I get an error 

`count():Parameter must be an array or an object that implements Countable `

PHP version: 7.3.11
OS: Mac OS Catalina

**Comment by crynobone** [comment]
Which version of `orchestra/foundation` or `laravel/framework` are you using at the moment?

can you run `composer show` and share the output.

**Comment by vbasky** [comment]
This is the output of `composer show`

`classpreloader/classpreloader         3.2.0   Helps class loading performance by generating a single PHP file containing all of the autoloaded fil...
danielstjules/stringy                 2.4.0   A string manipulation library with multibyte support
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base directory specification for php
doctrine/cache                        1.9.1   PHP Doctrine Cache library is a popular cache implementation that supports many different drivers su...
doctrine/dbal                         v2.10.0 Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection ...
doctrine/event-manager                1.1.0   The Doctrine Event Manager is a simple PHP event system that was built to be used with the various D...
doctrine/inflector                    1.3.1   Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.3.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
fzaninotto/faker                      v1.9.0  Faker is a PHP library that generates fake data for you.
hamcrest/hamcrest-php                 v1.2.2  This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       v0.2
jakub-onderka/php-console-highlighter v0.3.2
jeremeamia/superclosure               2.4.0   Serialize Closure objects, including their context and binding
kylekatarnls/update-helper            1.2.0   Update helper
laravel/framework                     v5.2.45 The Laravel Framework.
laravie/html                          v5.2.3  HTML and Form Builders for the Laravel Framework
league/flysystem                      1.0.57  Filesystem abstraction: Many filesystems, one API.
mockery/mockery                       0.9.11  Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHP...
monolog/monolog                       1.25.2  Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression             v1.2.1  CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
myclabs/deep-copy                     1.9.3   Create deep copies (clones) of your objects
nesbot/carbon                         1.39.1  A simple API extension for DateTime.
nikic/php-parser                      v2.1.1  A PHP parser written in PHP
orchestra/asset                       v3.2.1  Asset Component for Orchestra Platform
orchestra/auth                        v3.2.6  Auth Component for Orchestra Platform
orchestra/contracts                   v3.2.1  Contracts for Orchestra Platform
orchestra/control                     v3.2.1  Control Extension for Orchestra Platform
orchestra/extension                   v3.2.3  Extension Component for Orchestra Platform
orchestra/foundation                  v3.2.9  Orchestra Platform Foundation
orchestra/html                        v3.2.4  HTML Component for Orchestra Platform
orchestra/installer                   v3.2.2  Orchestra Platform Installer
orchestra/kernel                      v3.2.3  Kernel for Orchestra Platform
orchestra/memory                      v3.2.4  Memory Component for Orchestra Platform
orchestra/messages                    v3.2.1  Messages Component for Laravel and Orchestra Platform
orchestra/model                       v3.2.9  Model Component for Orchestra Platform
orchestra/notifier                    v3.2.4  User Notification Component for Orchestra Platform
orchestra/optimize                    v3.2.0  Optimize Component for Orchestra Platform
orchestra/publisher                   v3.2.1  Publisher Component for Orchestra Platform
orchestra/studio                      v3.2.3  Code Generator for Orchestra Platform
orchestra/support                     v3.2.4  Support Component for Orchestra Platform
orchestra/testbench                   v3.2.8  Laravel Package Unit Testing Helper
orchestra/testing                     v3.2.3  Orchestra Platform Testing Helper
orchestra/translation                 v3.2.0  Translation Component for Orchestra Platform
orchestra/view                        v3.2.1  View Component for Orchestra Platform
orchestra/widget                      v3.2.0  Widget Component for Orchestra Platform
paragonie/random_compat               v1.4.3  PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common       2.0.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.3.2   With this component, a library can provide support for annotations via DocBlocks or otherwise retrie...
phpdocumentor/type-resolver           1.0.1   A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                      1.9.0   Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             4.0.8   Library that provides collection, processing, and rendering functionality for PHP code coverage info...
phpunit/php-file-iterator             1.4.5   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.9   Utility class for timing
phpunit/php-token-stream              2.0.2   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       5.7.27  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.4.4   Mock Object library for PHPUnit
predis/predis                         v1.1.1  Flexible and feature-complete Redis client for PHP and HHVM
psr/log                               1.1.2   Common interface for logging libraries
psy/psysh                             v0.7.2  An interactive shell for modern PHP.
sebastian/code-unit-reverse-lookup    1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator                  1.2.4   Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.3   Diff implementation
sebastian/environment                 2.0.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    2.0.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1   Snapshotting of global state
sebastian/object-enumerator           2.0.1   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context           2.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer               v5.4.12 Swiftmailer, free feature-rich PHP mailer
symfony/console                       v3.0.9  Symfony Console Component
symfony/css-selector                  v3.0.9  Symfony CssSelector Component
symfony/debug                         v3.0.9  Symfony Debug Component
symfony/dom-crawler                   v3.0.9  Symfony DomCrawler Component
symfony/event-dispatcher              v3.4.35 Symfony EventDispatcher Component
symfony/finder                        v3.0.9  Symfony Finder Component
symfony/http-foundation               v3.0.9  Symfony HttpFoundation Component
symfony/http-kernel                   v3.0.9  Symfony HttpKernel Component
symfony/polyfill-ctype                v1.12.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring             v1.12.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                v1.12.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.12.0 Symfony utilities for portability of PHP codes
symfony/process                       v3.0.9  Symfony Process Component
symfony/routing                       v3.0.9  Symfony Routing Component
symfony/translation                   v3.0.9  Symfony Translation Component
symfony/var-dumper                    v3.0.9  Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.3.18 Symfony Yaml Component
tijsverkoyen/css-to-inline-styles     1.5.5   CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with...
vlucas/phpdotenv                      v2.6.1  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.5.0   Assertions to validate method input/output with nice error messages`

**Comment by crynobone** [comment]
That's outdated.

```
laravel/framework v5.2.45
```
You can simply create a new Orchestra Platform using 

```
composer create-project orchestra/platform
```

**Comment by vbasky** [comment]
I still get the same issue with a new `composer create-project orchestra/platform`

And this is my `composer show` this time

```
dnoegel/php-xdg-base-dir              0.1        implementation of xdg base directory s...
doctrine/cache                        1.9.1      PHP Doctrine Cache library is a popula...
doctrine/dbal                         v2.10.0    Powerful PHP database abstraction laye...
doctrine/event-manager                1.1.0      The Doctrine Event Manager is a simple...
doctrine/inflector                    1.3.1      Common String Manipulations with regar...
doctrine/instantiator                 1.3.0      A small, lightweight utility to instan...
doctrine/lexer                        1.2.0      PHP Doctrine Lexer parser library that...
dragonmantank/cron-expression         v2.3.0     CRON for PHP: Calculate the next or pr...
egulias/email-validator               2.1.11     A library for validating emails agains...
erusev/parsedown                      1.7.3      Parser for Markdown.
facade/flare-client-php               1.2.1      Send PHP errors to Flare
facade/ignition                       1.12.0     A beautiful error page for Laravel app...
facade/ignition-contracts             1.0.0      Solution contracts for Ignition
fideloper/proxy                       4.2.1      Set trusted proxies for Laravel
filp/whoops                           2.5.0      php error handling for cool kids
fzaninotto/faker                      v1.9.0     Faker is a PHP library that generates ...
hamcrest/hamcrest-php                 v2.0.0     This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       v0.2
jakub-onderka/php-console-highlighter v0.4       Highlight PHP code in terminal
laravel/browser-kit-testing           v5.1.3     Provides backwards compatibility for B...
laravel/framework                     v6.5.2     The Laravel Framework.
laravel/tinker                        v1.0.10    Powerful REPL for the Laravel framework.
laravie/authen                        v2.4.0     User Authentication Identifiers for La...
laravie/html                          v6.0.1     HTML and Form Builders for the Laravel...
laravie/query-filter                  v1.0.2     Database/Eloquent Query Builder filter...
league/flysystem                      1.0.57     Filesystem abstraction: Many filesyste...
mockery/mockery                       1.3.0      Mockery is a simple yet flexible PHP m...
monolog/monolog                       2.0.1      Sends your logs to files, sockets, inb...
myclabs/deep-copy                     1.9.3      Create deep copies (clones) of your ob...
nesbot/carbon                         2.27.0     An API extension for DateTime that sup...
nikic/php-parser                      v4.3.0     A PHP parser written in PHP
nunomaduro/collision                  v3.0.1     Cli error handling for console/command...
opis/closure                          3.4.1      A library that can be used to serializ...
orchestra/asset                       v4.0.0     Asset Component for Orchestra Platform
orchestra/auth                        v4.0.0     Auth Component for Orchestra Platform
orchestra/avatar                      v4.0.0     Avatar Component for Orchestra Platform
orchestra/contracts                   v4.1.0     Contracts for Orchestra Platform
orchestra/control                     v4.0.0     Control Extension for Orchestra Platform
orchestra/extension                   v4.0.1     Extension Component for Orchestra Plat...
orchestra/foundation                  v4.1.0     Orchestra Platform Foundation
orchestra/html                        v4.1.0     HTML Component for Orchestra Platform
orchestra/installer                   v4.0.0     Orchestra Platform Installer
orchestra/kernel                      v4.0.1     Kernel for Orchestra Platform
orchestra/memory                      v4.0.0     Memory Component for Orchestra Platform
orchestra/messages                    v4.0.0     Messages Component for Laravel and Orc...
orchestra/model                       v4.2.0     Model Component for Orchestra Platform
orchestra/notifier                    v4.0.1     User Notification Component for Orches...
orchestra/support                     v4.0.2     Support Component for Orchestra Platform
orchestra/testbench                   v4.4.1     Laravel Testing Helper for Packages De...
orchestra/testbench-browser-kit       v4.4.1     Laravel Browser Kit Testing Helper for...
orchestra/testbench-core              v4.4.1     Testing Helper for Laravel Development
orchestra/testing                     v4.1.2     Orchestra Platform Testing Helper
orchestra/translation                 v4.0.0     Translation Component for Orchestra Pl...
orchestra/view                        v4.0.0     View Component for Orchestra Platform
orchestra/widget                      v4.0.0     Widget Component for Orchestra Platform
paragonie/random_compat               v9.99.99   PHP 5.x polyfill for random_bytes() an...
phar-io/manifest                      1.0.3      Component for reading phar.io manifest...
phar-io/version                       2.0.1      Library for handling version informati...
phpdocumentor/reflection-common       2.0.0      Common reflection classes used by phpd...
phpdocumentor/reflection-docblock     4.3.2      With this component, a library can pro...
phpdocumentor/type-resolver           1.0.1      A PSR-5 based resolver of Class names,...
phpoption/phpoption                   1.5.2      Option Type for PHP
phpspec/prophecy                      1.9.0      Highly opinionated mocking framework f...
phpunit/php-code-coverage             7.0.10     Library that provides collection, proc...
phpunit/php-file-iterator             2.0.2      FilterIterator implementation that fil...
phpunit/php-text-template             1.2.1      Simple template engine.
phpunit/php-timer                     2.1.2      Utility class for timing
phpunit/php-token-stream              3.1.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       8.4.3      The PHP Unit Testing framework.
psr/container                         1.0.0      Common Container Interface (PHP FIG PS...
psr/log                               1.1.2      Common interface for logging libraries
psr/simple-cache                      1.0.1      Common interfaces for simple caching
psy/psysh                             v0.9.9     An interactive shell for modern PHP.
ramsey/uuid                           3.8.0      Formerly rhumsaa/uuid. A PHP 5.4+ libr...
scrivo/highlight.php                  v9.15.10.0 Server side syntax highlighter that su...
sebastian/code-unit-reverse-lookup    1.0.1      Looks up which function or method a li...
sebastian/comparator                  3.0.2      Provides the functionality to compare ...
sebastian/diff                        3.0.2      Diff implementation
sebastian/environment                 4.2.3      Provides functionality to handle HHVM/...
sebastian/exporter                    3.1.2      Provides the functionality to export P...
sebastian/global-state                3.0.0      Snapshotting of global state
sebastian/object-enumerator           3.0.3      Traverses array structures and object ...
sebastian/object-reflector            1.1.1      Allows reflection of object attributes...
sebastian/recursion-context           3.0.0      Provides functionality to recursively ...
sebastian/resource-operations         2.0.1      Provides a list of PHP built-in functi...
sebastian/type                        1.1.3      Collection of value objects that repre...
sebastian/version                     2.0.1      Library that helps with managing the v...
statamic/stringy                      3.1.1      A string manipulation library with mul...
swiftmailer/swiftmailer               v6.2.3     Swiftmailer, free feature-rich PHP mailer
symfony/console                       v4.4.0     Symfony Console Component
symfony/css-selector                  v4.4.0     Symfony CssSelector Component
symfony/debug                         v4.4.0     Symfony Debug Component
symfony/dom-crawler                   v4.4.0     Symfony DomCrawler Component
symfony/error-handler                 v4.4.0     Symfony ErrorHandler Component
symfony/event-dispatcher              v4.4.0     Symfony EventDispatcher Component
symfony/event-dispatcher-contracts    v1.1.7     Generic abstractions related to dispat...
symfony/finder                        v4.4.0     Symfony Finder Component
symfony/http-foundation               v4.4.0     Symfony HttpFoundation Component
symfony/http-kernel                   v4.4.0     Symfony HttpKernel Component
symfony/mime                          v5.0.0     A library to manipulate MIME messages
symfony/polyfill-ctype                v1.12.0    Symfony polyfill for ctype functions
symfony/polyfill-iconv                v1.12.0    Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn             v1.12.0    Symfony polyfill for intl's idn_to_asc...
symfony/polyfill-mbstring             v1.12.0    Symfony polyfill for the Mbstring exte...
symfony/polyfill-php72                v1.12.0    Symfony polyfill backporting some PHP ...
symfony/polyfill-php73                v1.12.0    Symfony polyfill backporting some PHP ...
symfony/process                       v4.4.0     Symfony Process Component
symfony/routing                       v4.4.0     Symfony Routing Component
symfony/service-contracts             v2.0.0     Generic abstractions related to writin...
symfony/translation                   v4.4.0     Symfony Translation Component
symfony/translation-contracts         v2.0.0     Generic abstractions related to transl...
symfony/var-dumper                    v4.4.0     Symfony mechanism for exploring and du...
theseer/tokenizer                     1.1.3      A small library for converting tokeniz...
tijsverkoyen/css-to-inline-styles     2.2.2      CssToInlineStyles is a class that enab...
vlucas/phpdotenv                      v3.6.0     Loads environment variables from `.env...
webmozart/assert                      1.6.0      Assertions to validate method input/ou...
```

**Comment by crynobone** [comment]
I have multiple app running on latest Orchestra Platform with PHP 7.3 so I'm not sure what missing in your installation.

**Comment by crynobone** [comment]
https://github.com/orchestral/installer/blob/4.x/tests/Controller/InstallerControllerTest.php

We also have Travis-CI verify the installation process on 7.2, 7.3 and 7.4snapshot.

**Comment by vbasky** [comment]
Will I be able to get any logs on the default installation that shows me where the error is happening ?

**Comment by crynobone** [comment]
> Will I be able to get any logs on the default installation that shows me where the error is happening ?

Logs are the same with Laravel logging component.
