### ISSUE TITLE
Website problem

### ISSUE THREAD

**Issue by realtebo** [orchestral/platform#69]
Hi !

I want only to warn you that 

http://cookbook.orchestraplatform.com/ give use an error about your CDN

Error 1014 Ray ID: 55f369c5da0f3d75 • 2020-02-03 09:35:09 UTC
CNAME Cross-User Banned

**Comment by crynobone** [comment]
Thank you for the report but the site is not actively maintain so that kinda expected.

**Comment by realtebo** [comment]
@crynobone ... I think this statement is enough to make use discard this framework for future projects.

**Comment by crynobone** [comment]
No problem with that. I personally use it for work at the moment and doesn't have enough time to handle website etc.
